### ISSUE TITLE
Sprint 1 - Hardening de Ubuntu;  Configuración de usuarios y grupos.

### ISSUE THREAD

**Issue by jmendozac-db** [cifpfbmoll/proyecto-seguridad-en-redes-corporativas-pedro-y-jose#2]
- **Configuración de usuarios y grupos. Crea un usuario administrador con tu nombre, y añade este al grupo sudoers. Además, aplica  una política de contraseñas adecuada.** 

· Complejidad
· Reutilización de contraseñas.
· Almacenamiento de contraseñas. Comprueba como un hash puede ser roto si el cifrado no es el adecuado. Sigue este tutorial.
· Ahora ya has evidenciado la importancia de realizar almacenamiento seguro de contraseñas como por ejemplo sha512. Una vez establecido vuelve a proceder el ataque.
· Configuración del entorno (Caducidad y cambio de contraseña, Timeout de inactividad, Bloqueo de cuenta tras varios intentos, etc)

**Comment by pedrosanchez21** [comment]
Ya he hecho los 3 primeros puntos, me queda la configuración del entorno

**Comment by pedrosanchez21** [comment]
Estoy en el minuto 13:06

**Comment by jmendozac-db** [comment]
_Mirar tablo de anuncios en caso de fallos_

1. John The Ripper y Hashcat
[](url) https://www.zonasystem.com/2020/06/password-cracking-en-linux-john-the-ripper-hashcat.html

2. Resetar contraseña de Ubuntu
[](url) https://parzibyte.me/blog/2019/07/04/resetar-contrasena-ubuyte.me/blog/2019/07/04/resetar-contrasena-ubuntu/)ntu/

3. Actualizar como root el Passwd
[](url) https://www.tecmint.com/fix-passwd-authentication-token-manipulation-error-in-linux/

**Comment by jmendozac-db** [comment]
Tarea  terminada, no hubieron complicaciones al usar el programa John the Ripper
